### ISSUE TITLE
Lua and Unicode

### ISSUE THREAD

**Issue by mancellin** [geg2102/nvim-python-repl#1]
Thank you for sharing this plugin. I have something a bit similar in my private config, so I've looked at your implementation with interest.

A quick comment, based on an issue I've had:
`string.sub` might not do what you want if the string has non-ascii characters. Lua does not handle multi-bytes utf-8 characters in the same way as e.g. Python. Instead, you might want to use `vim.fn.strcharpart()` and `vim.fn.strchars()`.

**Comment by zhangfuwen** [comment]
> Thank you for sharing this plugin. I have something a bit similar in my private config, so I've looked at your implementation with interest.
> 
> A quick comment, based on an issue I've had: `string.sub` might not do what you want if the string has non-ascii characters. Lua does not handle multi-bytes utf-8 characters in the same way as e.g. Python. Instead, you might want to use `vim.fn.strcharpart()` and `vim.fn.strchars()`.

hi, how to fix this? I encountered a similiar issue. #18 

I tried to modify it, but without luck.

what I've done:
```diff
diff --git a/lua/nvim-python-repl/nvim-python-repl.lua b/lua/nvim-python-repl/nvim-python-repl.lua
index 169c991..3139bee 100644
--- a/lua/nvim-python-repl/nvim-python-repl.lua
+++ b/lua/nvim-python-repl/nvim-python-repl.lua
@@ -112,16 +112,16 @@ local construct_message_from_selection = function(start_row, start_col, end_row,
     local bufnr = api.nvim_get_current_buf()
     if start_row ~= end_row then
         local lines = api.nvim_buf_get_lines(bufnr, start_row, end_row + 1, false)
-        lines[1] = string.sub(lines[1], start_col + 1)
+        lines[1] = vim.fn.strcharpart(lines[1], start_col)
         -- end_row might be just after the last line. In this case the last line is not truncated.
         if #lines == end_row - start_row then
-            lines[#lines] = string.sub(lines[#lines], 1, end_col)
+            lines[#lines] = vim.fn.strcharpart(lines[#lines], 0, end_col + 1)
         end
         return lines
     else
         local line = api.nvim_buf_get_lines(bufnr, start_row, start_row + 1, false)[1]
         -- If line is nil then the line is empty
-        return line and { string.sub(line, start_col + 1, end_col) } or {}
+        return line and { vim.fn.strcharpart(line, start_col, end_col - start_col + 1) }
     end
 end
```

**Comment by mancellin** [comment]
I don't if you still have the issue, but FYI the corresponding code in my private config now looks like this:

```lua
-- Return the content between two marks as a list of lines
local function lines_between_marks(mark1, mark2, is_charwise)
    local r1, c1 = unpack(vim.api.nvim_buf_get_mark(0, mark1))
    local r2, c2 = unpack(vim.api.nvim_buf_get_mark(0, mark2))
    local lines
    if is_charwise then
        lines = vim.api.nvim_buf_get_text(0, r1-1, c1, r2-1, c2+1, {})
    else
        lines = vim.api.nvim_buf_get_lines(0, r1-1, r2, true)
    end
    return lines
end
```
