### ISSUE TITLE
Issue on windows with git-bash and windows terminal

### ISSUE THREAD

**Issue by rustydagger312** [geg2102/nvim-python-repl#2]
Hi,

The purpose of this plug in is exactly what I'm looking for. I'm very thankful for that. 

But I assume it's written on linux. Unfortunately, I'm stuck on windows these days, running nvim 7.0 on top of windows terminal and git bash. 

There are two issues if you can help me figure out:
1. What's purpose of initial "[200 ..[200~" sequence? On my setup, the sequence gets print out in the buffer instead of intended purpose. I guess.
2. The <cr> at the end of line doesn't get sent or accepted because I have to switch to ipython buffer to press return. 

Any idea/suggestions are appreciated.

Thanks,
XQ

**Comment by ArthurHowardMorris** [comment]
Point number 2: this is the default, you can change it to execute when you send the selection to the repl.

```
require("nvim-python-repl").setup({
    execute_on_send=true, --default is false 
    vsplit=false,
    spawn_command={
        python="ipython", 
        scala="sbt console",
        lua="ilua"
    }
}) 
```
