### ISSUE TITLE
Installation Trouble

### ISSUE THREAD

**Issue by MartinHeroux** [geg2102/nvim-python-repl#4]
Sorry to have to ask this here. I have used vim (basic neovim, no lua) in the past, but would like to get back to using it as my main Python IDE if possible. 

A key requirement for me is to have the functionality that nvim-python-repl offers.

I have tried to install your package using a few different combinations, but because I am relatively new to lua, lazy, etc, I have not been able to crack it. Hopefully I am not the only person who will run into this issue and that whatever I learn I can contribute back to the documentation of the projects to help others in the future.

**What I have tried**

I have opted to go with NvChad to have a decent starting point for NeoVim. The structure and content of my .config/nvim folder is as follows: 

```bash 
├── init.lua
├── lazy-lock.json
├── LICENSE
└── lua
    ├── after
    │   └── plugin
    │       └── keymaps.lua
    ├── core
    │   ├── bootstrap.lua
    │   ├── default_config.lua
    │   ├── init.lua
    │   ├── mappings.lua
    │   └── utils.lua
    ├── custom
    │   ├── chadrc.lua
    │   ├── configs
    │   │   ├── lspconfig.lua
    │   │   └── null-ls.lua
    │   ├── init.lua
    │   ├── mappings.lua
    │   └── plugins.lua
    └── plugins
        ├── configs
        │   ├── cmp.lua
        │   ├── lazy_nvim.lua
        │   ├── lspconfig.lua
        │   ├── mason.lua
        │   ├── nvimtree.lua
        │   ├── others.lua
        │   ├── telescope.lua
        │   └── treesitter.lua
        └── init.lua

```

I added the recommended text to the `.config/nvim/lua/plugins/init.lua` file so that it can be installed by lazy:

```lua
{
    "geg2102/nvim-python-repl",
    dependencies = "nvim-treesitter",
    ft = {"python", "lua", "scala"}, 
    config = function()
        require("nvim-python-repl").setup({
            execute_on_send = false,
            vsplit = false,
        })
    end
}
```

When I restarted nvim, lazy vim indicated that it noticed and installed your package:

![image](https://github.com/geg2102/nvim-python-repl/assets/12129388/911dd3dc-14b1-4bf7-b297-6a58c7eb7e12)

Then I added the following text to the `./config/nvim/lua/custom/init.lua` file:

'''lua
require("nvim-python-repl").setup()
'''

When I restarted vim I go the following error message:

```
Error detected while processing /home/martin/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/martin/.config/nvim/lua/custom/init.lua:2: module 'nvim-python-repl' not found:
        no field package.preload['nvim-python-repl']
        no file './nvim-python-repl.lua'
        no file '/usr/share/luajit-2.1.0-beta3/nvim-python-repl.lua'
        no file '/usr/local/share/lua/5.1/nvim-python-repl.lua'
        no file '/usr/local/share/lua/5.1/nvim-python-repl/init.lua'
        no file '/usr/share/lua/5.1/nvim-python-repl.lua'
        no file '/usr/share/lua/5.1/nvim-python-repl/init.lua'
        no file './nvim-python-repl.so'
        no file '/usr/local/lib/lua/5.1/nvim-python-repl.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/nvim-python-repl.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/martin/.config/nvim/lua/custom/init.lua:2: in main chunk
        [C]: in function 'dofile'
        /home/martin/.config/nvim/init.lua:6: in main chunk
```
I also tried to place the line in the main, top level init.lua file but go the same error.

Would it be possible to get a little guidance on what I am doing wrong and hopefully get the package working? 

Much appreciated.

**Comment by Alan-Manning** [comment]
i think you may not need that line you added to the init.lua file. Lazy will try to load that plugin when it sees it. I dont know exactly what happens in nvchad but if you have that first bit of code in your config with the other plugins you dont need the second bit of code requireing the .setup(). config section of the first code snippet gets run when the plugin is loaded i believe, which already has that setup in it with those config options. so maybe jsut have the first code snippet and remove the single line you poseted. im not an expert tho, no idea if that doesnt work.

**Comment by MartinHeroux** [comment]
Thanks. I have moved to a minimalist install in order to slowly build up my
tools (and also understand what everything is doing).

I now have a working version of nvim that I am happy with...bar the python
repl. So I will try and add nvim-python-repl over the weekend and get back
to you.

Cheers,

Marty
